<?php
require_once 'vendor/autoload.php';

// Create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetCreator('Your Name');
$pdf->SetAuthor('Your Name');
$pdf->SetTitle('Database Table to PDF');
$pdf->SetSubject('Database Table');
$pdf->SetKeywords('TCPDF, PDF, database, table');

// Set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, 'Database Table', 'Generated by TCPDF');

// Set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Add a page
$pdf->AddPage();

// Set font
$pdf->SetFont('freeserif', '', 11.5);

// Fetch data from the users table
include("database.php"); // Assuming this file contains your database connection code
$sql = "SELECT * FROM people";
$result = $conn->query($sql);

// Initialize table
$html = '<table border="1" cellpadding="4" cellspacing="0">';
$html .= '<tr bgcolor="#CCE5FF">';
$html .= '<th>ID</th>';
$html .= '<th>Имена</th>';
$html .= '<th>Компания</th>';
$html .= '<th>Адрес</th>';
$html .= '<th>Мобилен</th>';
$html .= '<th>Стационарен</th>';
$html .= '<th>Факс</th>';
$html .= '</tr>';

// Add data rows
if ($result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        $html .= '<tr>';
        $html .= '<td>' . $row["id"] . '</td>';
        $html .= '<td>' . $row["name"] . '</td>';
        $html .= '<td>' . $row["company"] . '</td>';
        $html .= '<td>' . $row["address"] . '</td>';
        $html .= '<td>' . $row["mobile"] . '</td>';
        $html .= '<td>' . $row["stat"] . '</td>';
        $html .= '<td>' . $row["fax"] . '</td>';
        $html .= '</tr>';
    }
}

$html .= '</table>';

// Output the HTML content
$pdf->writeHTML($html, true, false, true, false, '');

// Close and output PDF document
$pdf->Output('database_table.pdf', 'D');

// Close the database connection
$conn->close();
